# 描述/签名
name: 刻莱诺图书馆
description: Kelaino Library

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url: https://thelemia.github.io
# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: /book

# [可选]博客logo图片URL，建议尺寸不超过300px × 300px
avatar: https://ovo.wxw.media/media_attachments/files/109/310/828/701/996/843/original/62f95928bd0b6a3c.png
# [可选]favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://ovo.wxw.media/media_attachments/files/109/310/828/701/996/843/original/62f95928bd0b6a3c.png

# 菜单中的按钮
navigation:
  - name: 首页
    url: https://thelemia.github.io/home
  - name: 关于
    url: https://thelemia.github.io/about
  - name: 归档
    url: https://thelemia.github.io/book
  - name: 标签
    url: https://thelemia.github.io/tags

# 每页的文章数
paginate: 10

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  weibo: https://weibo.com/5018395824/profile?rightmod=1&wvr=6&mod=personinfo  #微博个性域名
  twitter: # https://www.twitter.com/<your_twitter_username> 
  email: witchstaynight@gmail.com #youremailaddress@mail.com

# 站点页脚的文字
footer-text: Copyright (c) 2022 刻莱诺图书馆

# 评论，注意，请不要同时添加多种不同的评论区
# 输入Disqus shortname，即可添加评论区，请查阅文档，设置自己的disqus站点，不要继续使用我的站点loffer
disqus: thelemia #shortname

# 输入Gitalk相关设定，即可添加评论区，具体请看教程
# gitalk:
#   clientID: 
#   clientSecret: 
#   repo: 
#   owner: 
#   proxy:

# 输入Google Analytics web tracking code
# google_analytics:
# utteranc:
#   repo: # Your github repo path, also see: https://utteranc.es

# !! 以下所有设置都不需要更改 !!

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

